# Generated by Django 3.1.7 on 2021-04-22 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('private_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.ImageField(blank=True, upload_to='')),
                ('domain_name', models.CharField(blank=True, max_length=256, verbose_name='domain name')),
                ('html_content', models.TextField(verbose_name='HTML content')),
                ('css', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified at')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_websites', to='builder.template', verbose_name='Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
        ),
        migrations.CreateModel(
            name='UploadedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('asset', models.FileField(upload_to='assests/', verbose_name='asset')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
