# Generated by Django 3.1.7 on 2021-04-26 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_url', models.URLField(blank=True)),
                ('cloudfront_url', models.URLField(blank=True)),
                ('user_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sites', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_sites', to='websites.website')),
            ],
        ),
    ]
