# Generated by Django 3.1.7 on 2021-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_hostedwebsite_certificate_arn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='domain name'),
        ),
    ]
