# Generated by Django 3.1.7 on 2021-05-03 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_auto_20210427_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedwebsite',
            name='distribution_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hostedwebsite',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sites', to='websites.website'),
        ),
        migrations.AlterField(
            model_name='website',
            name='domain_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^(?!http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', 'Domain is not valid (do not use http(s)://)')], verbose_name='domain name'),
        ),
    ]
