# Generated by Django 3.1.7 on 2021-07-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_auto_20210515_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteExtraPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50)),
                ('name', models.CharField(default='index', max_length=128, verbose_name='name')),
                ('html_content', models.TextField(default='', verbose_name='html content')),
                ('css', models.TextField(blank=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='websites.website')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'abstract': False,
            },
        ),
    ]
