# Generated by Django 3.1.7 on 2021-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_websiteextrapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
