# Generated by Django 3.1.7 on 2021-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_website_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, help_text='this will be your subdomain, example: mysite.ngye.in', null=True, unique=True, verbose_name='Subdomain'),
        ),
    ]
