# Generated by Django 3.1.7 on 2021-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_hu',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
