# Generated by Django 3.1.7 on 2021-07-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210423_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='asset_size',
            field=models.BigIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_host_website_on_aws',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='form_submissions',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_hu',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
