# Generated by Django 3.1.7 on 2021-07-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210719_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='asset_size',
            field=models.BigIntegerField(default=1024000000),
        ),
    ]
