# Generated by Django 3.1.7 on 2021-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='block',
            name='name_hu',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='blockcategory',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='blockcategory',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='template',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='template',
            name='description_hu',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='template',
            name='name_hu',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='description_hu',
            field=models.TextField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='templatecategory',
            name='name_hu',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
    ]
