# Generated by Django 3.1.7 on 2021-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20210423_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='script',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='builder.Script'),
        ),
        migrations.RemoveField(
            model_name='block',
            name='style',
        ),
        migrations.AddField(
            model_name='block',
            name='style',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='builder.Style'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
