# Generated by Django 3.1.7 on 2021-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_script_is_defered'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='info_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
