# Generated by Django 3.1.7 on 2021-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_block_info_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AddField(
            model_name='template',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='is editable'),
        ),
    ]
