# Generated by Django 3.1.7 on 2021-07-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_auto_20210525_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50)),
                ('name', models.CharField(default='index', max_length=128, verbose_name='name')),
                ('html_content', models.TextField(default='', verbose_name='html content')),
                ('css', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='extra_pages',
            field=models.ManyToManyField(blank=True, to='builder.Page'),
        ),
    ]
