# Generated by Django 3.1.7 on 2021-07-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_auto_20210707_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateExtraPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50)),
                ('name', models.CharField(default='index', max_length=128, verbose_name='name')),
                ('html_content', models.TextField(default='', verbose_name='html content')),
                ('css', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='template',
            name='extra_pages',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='templateextrapage',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.template'),
        ),
    ]
